global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: computing_lab_may_2026
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - app:8080
